### ISSUE TITLE
la apk no permite agregar imágenes

### ISSUE THREAD

**Issue by pancram** [AngelJRomero21/RedLinuxClick#1]
Angel, éste es un recordatorio para que revises el tema de los permisos en la apk de android de linux click, para así poder agregar imágenes a los posteos

**Comment by JoaquinDecima** [comment]
En el navegador te permite?

**Comment by AngelJRomero21** [comment]
> En el navegador te permite?

Lo que sucede es que la apk no tiene puesto para pedir permisos de almacenamiento, camara y audio.

Supongo que en el navegador le deja!

**Comment by JoaquinDecima** [comment]
Ahhh ok por eso preguntaba, la siguiente versión debería pedir los permisos...

**Comment by AngelJRomero21** [comment]
> Ahhh ok por eso preguntaba, la siguiente versión debería pedir los permisos...

Si ya actualice el codigo ahora si debe permitir, dentro de unos minutos saco una actualizacion.

> Angel, éste es un recordatorio para que revises el tema de los permisos en la apk de android de linux click, para así poder agregar imágenes a los posteos

**Comment by AngelJRomero21** [comment]
Solucionado.

Se Añdieron Permisos

**Comment by AngelJRomero21** [comment]
https://github.com/AngelJRomero21/RedLinuxClick/releases/tag/v1.0.3

Descargar Nueva Version

**Comment by AngelJRomero21** [comment]
Reabro Porque la app en algunas versiones android no funciona bien lo de los permisos

**Comment by reynyrs** [comment]
solucionado?

**Comment by AngelJRomero21** [comment]
https://github.com/AngelJRomero21/RedLinuxClick/releases/tag/v1.0.6

SOLUCIONADO
