### ISSUE TITLE
Signing key changed?

### ISSUE THREAD

**Issue by IzzySoft** [AngelJRomero21/RedLinuxClick#6]
My updater just blocked the latest release, saying the signature does not match. Looking into it, it indeed seems the current release is using a different signing key (sha256: `bbf426115485f38ae0b92407f0c2e84ffff47266d00fc9c5fa6fd372a2577e04`) than v1.0.6 used (sha256: `2d94a17178869d549e9810434ef5b9138af8e8182b79e516d49e8c60937ff9ea`.

May I ask what happened?

**Comment by AngelJRomero21** [comment]
Hola! La firma es similar a la de la v1.0.6, solo que la que la version que
tenian subido en izzydroid no estaba firmada por lo que el actualizador
detecta que es una forma deiferente.

**Comment by IzzySoft** [comment]
> solo que la que la version que tenian subido en izzydroid no estaba firmada

The version at IzzyOnDroid (i.e. in my repo) is downloaded from releases here. And it must have been signed, else there would be no signing key reported. Let me check:

```bash
$ apkcert com.cromstudio.redlinuxclick_11.apk  # v1.2.3, versionCode:11
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Number of signers: 1
Signer #1 certificate DN: CN=Angel J. Romero, OU=CEO, O=Crom Studio, L=Guanare, ST=Portuguesa, C=3350
Signer #1 certificate SHA-256 digest: bbf426115485f38ae0b92407f0c2e84ffff47266d00fc9c5fa6fd372a2577e04
Signer #1 certificate SHA-1 digest: e53388b8296fb93fe43c4d933f15428fcaa890e4
Signer #1 certificate MD5 digest: 29de2a88678ce18191a872631bf5cc49
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: f1c833833b4bbaef95c2d76e73903c1d714a454ec63e9e785a11f5db02dc1e04
Signer #1 public key SHA-1 digest: 6491db11ca2cd21f501df9c24c558f0171ec8e64
Signer #1 public key MD5 digest: 795f9e9086d6667acc44070fa4fc8c78
```

Now for the previous one:

```bash
$ apkcert com.cromstudio.redlinuxclick_6.apk # v1.0.6, versionCode:6
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Number of signers: 1
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: 2d94a17178869d549e9810434ef5b9138af8e8182b79e516d49e8c60937ff9ea
Signer #1 certificate SHA-1 digest: ba0699eff5bb90830c5c1f3128c3527d68843556
Signer #1 certificate MD5 digest: dd69f439f7c805027d9ee7cc5e61359f
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: e136b478882de1c0737d911182437a6dee6acec113d9900631c381756486af34
Signer #1 public key SHA-1 digest: a1f6753c2b30c38f01d3e68775515cc128ee50c0
Signer #1 public key MD5 digest: 51ec9a66b088bea44e0a318f29ed561e
```

Err… A debug key was used for the previous one, I see. But v1.0.3 and v1.0.2 had been signed with a release key as well – again a different one:

```bash
Signer #1 certificate DN: CN=Romero Angel, OU=CEO, O=Crom Studio, L=Guanare, ST=Portuguesa, C=3350
Signer #1 certificate SHA-256 digest: 9c8807dfda36d6efef894e3fd5a2b3ba0f18a7fba975cdfcf9430bbce7c73c02
Signer #1 certificate SHA-1 digest: d4ff2e3b404a7ad94c7e568a09cfb802f9a33c0f
Signer #1 certificate MD5 digest: 006ddf3859f6e5ecc8761ccc586198a7
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: 63c219d5dc32337ce37b2722355014382febd6733ec1cc6b7628529d70ede828
Signer #1 public key SHA-1 digest: e6167224c90a0d714649247c522d237bfae6a1f1
Signer #1 public key MD5 digest: f560a57ee465d9c5fb0ccdc79867f0a9
```

So no offense meant, but how can I tell it's really Angel Romero I'm communicating with – and not just someone who gained access to this account? That's what signing keys are supposed to do on APKs. It would be much preferable if you could keep using the very same signing key you started with. Is that possible?

**Comment by AngelJRomero21** [comment]
Te indico, sucede que las firmas con las que inicie en las versiones
anteriores estaban en un PC el cuál perdió toda la información y perdió la
clave, a lo cual en la versión 1.0.6 se hizo de manera de depuración pero
luego se firmó, le había escrito en su repositorio donde indicaba que
actualizara la versión con la firma, usted me indico que en próximas
versiones se incluiría.

Dichas próximas versiones son la publicadas ayer.

Si revisas la diferencias de código no hay mucha diferencia solo
actualización del código y reducción de tamaño.

Hay alguna forma de mostrarle que verdaderamente soy Angel Romero?

Puede verificar que la versión publicada en Play Store incluye está misma
nueva firma.

**Comment by IzzySoft** [comment]
Thanks for the details! Switching to the new one here then. Please take good care of your current signing key; ideally make a backup off-device, like on some USB stick to keep in a safe place. v1.2.3 will go live in my repo with the next sync, previous versions will become unavailable here. All the best then!

**Comment by AngelJRomero21** [comment]
🫂 Gracias
